const scores = [
    {
        "chartId": "axe611acu8",
        "difficulty": "Master",
        "rank": "A",
        "pseudo": "Nenes",
        "score": "21234",
        "accuracy": "87.34",
        "date": new Date(),
    },
    {
        "chartId": "axe611acu8",
        "difficulty": "Master",
        "rank": "A",
        "pseudo": "Megumi",
        "score": "21224",
        "accuracy": "84.34",
        "date": new Date(),
    },
    {
        "chartId": "our1110t+p8",
        "difficulty": "Expert",
        "rank": "A",
        "pseudo": "MrDuck",
        "score": "2123",
        "accuracy": "80.34",
        "date": new Date(),
    },
    {
        "chartId": "mil57mil4",
        "difficulty": "Expert",
        "rank": "A",
        "pseudo": "Nenes",
        "score": "21234",
        "accuracy": "87.34",
        "date": new Date(),
    },
    {
        "chartId": "axe611acu8",
        "difficulty": "Advance",
        "rank": "A",
        "pseudo": "Megumi",
        "score": "21224",
        "accuracy": "84.34",
        "date": new Date(),
    },
    {
        "chartId": "mil57mil4",
        "difficulty": "Expert",
        "rank": "A",
        "pseudo": "MrDuck",
        "score": "2123",
        "accuracy": "80.34",
        "date": new Date(),
    },
    {
        "chartId": "pandora_paradoxxx",
        "difficulty": "Expert",
        "rank": "S",
        "pseudo": "Nenes",
        "score": "21233",
        "accuracy": "98,03",
        "date": new Date(),
    }
]

module.exports = scores;